# 1. 베이스 이미지 설정 (Python 3.10)
FROM python:3.9-slim

# 2. 작업 디렉터리 생성 및 설정


# 3. 로컬 파일을 컨테이너 내부로 복사
COPY requirements.txt ./

# 4. 필요 패키지 설치
RUN pip install -r requirements.txt

# 5. 컨테이너 실행 시 실행될 명령어

